---
name: IncompatibleAPIPluginLoader
main: Sandertv\IncompatibleApiPluginLoader\IncompatibleApiPluginLoader
api:
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
author: Sandertv
description: Allows enabling all plugins, disregarding the API version of it.
load: POSTWORLD